version: "3.8"
services:
  admin-frontend:
    build: .
    container_name: apna-ustad-admin
    restart: always
    ports:
      - "3001:4173"
    environment:
      # - VITE_API_URL=https://api.apnaustad.app/api/v1
      - VITE_API_URL=http://localhost:5001/api/v1
