/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWalletsRouteImport } from './routes/_admin.wallets'
import { Route as AdminVerificationRouteImport } from './routes/_admin.verification'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminSupportRouteImport } from './routes/_admin.support'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/_admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/_admin.reports'
import { Route as AdminPromosRouteImport } from './routes/_admin.promos'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminJobsRouteImport } from './routes/_admin.jobs'
import { Route as AdminDisputesRouteImport } from './routes/_admin.disputes'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'
import { Route as AdminBookingsRouteImport } from './routes/_admin.bookings'
import { Route as AdminAuditRouteImport } from './routes/_admin.audit'
import { Route as AdminAdminsRouteImport } from './routes/_admin.admins'
import { Route as AdminWorkersIndexRouteImport } from './routes/_admin.workers.index'
import { Route as AdminWorkersIdRouteImport } from './routes/_admin.workers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersIndexRoute = AdminWorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersIdRoute = AdminWorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AdminAdminsRoute
  '/audit': typeof AdminAuditRoute
  '/bookings': typeof AdminBookingsRoute
  '/categories': typeof AdminCategoriesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/disputes': typeof AdminDisputesRoute
  '/jobs': typeof AdminJobsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/promos': typeof AdminPromosRoute
  '/reports': typeof AdminReportsRoute
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
  '/verification': typeof AdminVerificationRoute
  '/wallets': typeof AdminWalletsRoute
  '/workers/$id': typeof AdminWorkersIdRoute
  '/workers/': typeof AdminWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AdminAdminsRoute
  '/audit': typeof AdminAuditRoute
  '/bookings': typeof AdminBookingsRoute
  '/categories': typeof AdminCategoriesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/disputes': typeof AdminDisputesRoute
  '/jobs': typeof AdminJobsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/promos': typeof AdminPromosRoute
  '/reports': typeof AdminReportsRoute
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
  '/verification': typeof AdminVerificationRoute
  '/wallets': typeof AdminWalletsRoute
  '/workers/$id': typeof AdminWorkersIdRoute
  '/workers': typeof AdminWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admins': typeof AdminAdminsRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/disputes': typeof AdminDisputesRoute
  '/_admin/jobs': typeof AdminJobsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/promos': typeof AdminPromosRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/support': typeof AdminSupportRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/verification': typeof AdminVerificationRoute
  '/_admin/wallets': typeof AdminWalletsRoute
  '/_admin/workers/$id': typeof AdminWorkersIdRoute
  '/_admin/workers/': typeof AdminWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/audit'
    | '/bookings'
    | '/categories'
    | '/dashboard'
    | '/disputes'
    | '/jobs'
    | '/notifications'
    | '/promos'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/support'
    | '/users'
    | '/verification'
    | '/wallets'
    | '/workers/$id'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/audit'
    | '/bookings'
    | '/categories'
    | '/dashboard'
    | '/disputes'
    | '/jobs'
    | '/notifications'
    | '/promos'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/support'
    | '/users'
    | '/verification'
    | '/wallets'
    | '/workers/$id'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/admins'
    | '/_admin/audit'
    | '/_admin/bookings'
    | '/_admin/categories'
    | '/_admin/dashboard'
    | '/_admin/disputes'
    | '/_admin/jobs'
    | '/_admin/notifications'
    | '/_admin/promos'
    | '/_admin/reports'
    | '/_admin/reviews'
    | '/_admin/settings'
    | '/_admin/support'
    | '/_admin/users'
    | '/_admin/verification'
    | '/_admin/wallets'
    | '/_admin/workers/$id'
    | '/_admin/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/wallets': {
      id: '/_admin/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/verification': {
      id: '/_admin/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support': {
      id: '/_admin/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/promos': {
      id: '/_admin/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/jobs': {
      id: '/_admin/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/disputes': {
      id: '/_admin/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admins': {
      id: '/_admin/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workers/': {
      id: '/_admin/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AdminWorkersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workers/$id': {
      id: '/_admin/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof AdminWorkersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWorkersIdRoute: typeof AdminWorkersIdRoute
  AdminWorkersIndexRoute: typeof AdminWorkersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWorkersIdRoute: AdminWorkersIdRoute,
  AdminWorkersIndexRoute: AdminWorkersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
